title: Davide Benvegnu
subtitle: DevOps Architect, International Speaker, MMA fighter
description: >- # this means to ignore newlines until "baseurl:"
  Davide Benvegnu's website

url: "https://devlopr.netlify.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Projects
      url: /projects
    - text: Talks
      url: /talks
#    - text: Shop
#      url : /shop/
    - text: Contact Me
      url : /contact
    

# Edit these details 

author_logo: profile.jpg
author: Davide Benvegnu
welcome_message:  >-
  This website is always work-in-progress, so it won't be ever ready. :-) 
  <br/>
  It aims to be an open channel for information and connection with the outside world; inside it you will find all of my areas of interest, my hobbies, my passions and some curiosity about my life. 
author_bio: >-
  OK... <i>let me introduce my self. </i>
  <br/><br/>
  My name is <b>Davide Benvegnù</b>, I was born on July 15th, 1984 in Trieste, a city where I lived for many years. After a "Tuscan moment", having moved to the charming city of Subbiano, now I live and work in Hong Kong.
  <br/><br/>
  I deal mainly in computer science, at various levels. Currently I am <b>DevOps Architect</b> for Microsoft, and I used to be a <a href="https://mvp.microsoft.com/en-us/PublicProfile/5001160?fullName=Davide%20Benvegn%C3%B9" target="_blank">Microsoft MVP in Visual Studio Application Lifecycle Management</a> (ALM) for 3 years in a row.
  <br/><br/>
  I'm a staff member of <a href="http://www.dotnettoscana.org/" target="_blank">DotNetToscana</a>, an official Microsoft technical <b>community</b>, where I organize events and have speeches at technical conferences about DevOps, the .Net world, Azure, containers and serverless.
  <br/>
  I'm also the founder of the <a href="http://www.hkmsc.org/" target="_blank">HKMSC - Hong Kong Microsoft Community</a>.
  <br/><br/>
  I have been practicing Mixed Martial Arts (<b>MMA</b>) for some time before moving to Hong Kong, with the Spartan Club Arezzo. Now I train at Impakt, with some of the best fighters in Hong Kong.
  <br/><br/>
  I also like the modern and contemporary art, especially abstract paintings.  
author_email: "davide.benvegnu@outlook.com"
author_location: Hong Kong
author_website_url: "http://www.davidebenvegnu.com"

author_work_experiences: 
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: DevOps Architect
              description: Empowering every person and organization on the planet to achieve more, with Azure DevOps.
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Global Cloud Solution Architect
              description: Worked on various Azure Cloud projects in the Telco, FSI, Retail, Logistics and Infrastructure business 
              visibility: true
            - company_name: DBTek
              company_logo: DBTeklogo.png
              company_url: http://www.dbtek.com.hk
              designation: Director & CTO
              #description: Worked on various Azure Cloud projects in the Telco, FSI, Retail, Logistics and Infrastructure business 
              visibility: true
            - company_name: Aruba
              company_logo: aruba.svg
              company_url: https://www.aruba.it
              designation: International Development Manager
              description: Managed 3 offshore teams, for a total of 30 people, working on the internal Public Cloud platform, Certified Email platform and an end-to-end ALM and DevOps system
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: false

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Azure WebApp SSL Manager
                project_description: An Azure Function that acquires and manages free SSL certificates for Azure Web App hosted applications.
                project_url: https://github.com/n3wt0n/AzureWebAppSSLManager
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: BugGuardian
                project_description: An Open Source library that allows to easily create a Bug work item on your Azure Devops account or on your on-premises Team Foundation Server 2015+ and Azure DevOps Server in case your application throws an Unhandled Exception.
                project_url: https://github.com/n3wt0n/BugGuardian
                project_nuget: https://www.nuget.org/packages/DBTek.BugGuardian
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Crypto
                project_description: An Open Source piece of software, Crypto is a library to Encrypt/Decript and Hash files and strings
                project_url: https://github.com/n3wt0n/Crypto
                project_nuget: https://www.nuget.org/packages/DBTek.Crypto
                visibility: true

# social links
twitter_username: davidebenvegnu
github_username:  n3wt0n
facebook_username: davide.benvegnu
linkedin_username: davidebenvegnu
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#lickr_username: johndoe

#for comments using disqus
#disqus_shortname: sujay-kundu  

# wakatime username (coding activity)
wakatime_username: davide.benvegnu@outlook.com

# formspree (contact form)
formspree_email: davide.benvegnu@outlook.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
#google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
#algolia:
#  application_id: D9WA1YKTRQ
#  index_name: blog_posts # You can replace that with whatever name you want
#  files_to_exclude: []
#  nodes_to_index: 'article'
#  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
