title: Davide Benvegnu
subtitle: DevOps Architect, International Speaker, MMA fighter
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://devlopr.netlify.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
#    - text: Shop
#      url : /shop/
    - text: Contact Me
      url : /contact
    

# Edit these details 

author_logo: profile.jpg
author: Davide Benvegnu
welcome_message: Welcome. This website is always work-in-progress, so it won't be ever ready. :-) It aims to be an open channel for information and connection with the outside world; inside it you will find all of my areas of interest, my hobbies, my passions and some curiosity about my life. 
author_bio: Hi, My Name is John Doe. I love to Code and Design. devlopr-jekyll is a theme built for developers.  
author_email: "davide.benvegnu@outlook.com"
author_location: Hong Kong
author_website_url: "http://www.davidebenvegnu.com"

author_work_experiences: 
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: DevOps Architect
              description: Empowering every person and organization on the planet to achieve more, with Azure DevOps.
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Global Cloud Solution Architect
              description: Worked on various Azure Cloud projects in the Telco, FSI, Retail, Logistics and Infrastructure business 
              visibility: true
            - company_name: DBTek
              company_logo: DBTeklogo.png
              company_url: http://www.dbtek.com.hk
              designation: Director & CTO
              #description: Worked on various Azure Cloud projects in the Telco, FSI, Retail, Logistics and Infrastructure business 
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: false

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: true

# social links
twitter_username: davidebenvegnu
github_username:  n3wt0n
facebook_username: davide.benvegnu
linkedin_username: davidebenvegnu
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#lickr_username: johndoe

#for comments using disqus
#disqus_shortname: sujay-kundu  

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# formspree (contact form)
formspree_email: davide.benvegnu@outlook.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
#google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
#algolia:
#  application_id: D9WA1YKTRQ
#  index_name: blog_posts # You can replace that with whatever name you want
#  files_to_exclude: []
#  nodes_to_index: 'article'
#  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/